### PR TITLE
[FRE-385] Show USD values for in and out asset

### PR DESCRIPTION
**Pull request by grikomsn**
## Description

This PR adds the USD value for both in and out asset using `https://coins.llama.fi/prices/current/coingecko:${id}` endpoint.

## Screenshots/Videos

https://github.com/skip-mev/ibc-dot-fun/assets/8220954/4390f2fe-97b9-4831-8c4f-ef52baf6d9ca

### CODE REVIEW

**Comment by grikomsn** [comment]
FRE-385

**Comment by MaghnusM** [comment]
Can we have the number off to the side instead? I.e. the gray usd amount on the far right

I think it will be less confusing than having it below

**Comment by grikomsn** [comment]
@MaghnusM as in directly on the right of the input? with same size but gray faded?

**Comment by grikomsn** [comment]
@MaghnusM case in point, wip adding diff percentage on in and out usd values, which makes sense if located below

|negative|positive|
|-|-|
|image|image|

**Review by MaghnusM — APPROVED** [review]

**Pull request merged**
